server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jiaming?serverTimezone=GMT%2B8&userSSL=false&characterEncoding=utf-8
    username: root
    password: mingge123
    driver-class-name: com.mysql.cj.jdbc.Driver
  cache:
    type: redis
  data:
    redis:
      password: wzm123

oauth2:
  jwk:
    private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCwo+gmg/Z4BeIvSpv1E9tLlesty1AJ83Y/yibiKfbjLWhGN9BDCX+1+SPFCoYpiJy4WFEtAED+mgcqmolofUmlWEppO/8G4vLROohOkJy94nKEhYD+fhIQS0esNYPN+OR6Nhm/rIq3LTCP4ucYukoY5l4sTOs2J10elVZl46mFG5+r4sUg4uTuoe4k3KTqibaLGOhb/LSftDutnZyvkqwt3ZnP286+RxspthcYha50kb4z6ss5TXrbyut6dFRt9hhrRxjN9wNTkeRBlNqM5LDDyGHhrTbKwc+ZBlfxvAzPlLLYS/HGUVSONapTfCCuYIHANXVmqTLAaunHftnzwOVdAgMBAAECggEAJDKSgkIMoe/it/o8F27oQ4cHWK0PS9q+YrgUW8hptYg6lBkf7nzl1O6nK9vKPnymUQiYKfahWwtJaKueePEjxGRha0tGKa0cQVATWrY7yJW9DfclxgEjxn8Gwv18cxsMBxdLE4JSMtNp3jKLVP/n605aAg4JLWHHrVrBB8Qtmv8E+aj50/tMjM522/zCd+6o2FI6P8vgwwyKeAYD1Syvipf86tqsol4oBxEJ2bNrrMp9uu2r776GEPPyhhIhzYcgoL7hMZ1gFg+MtGjo5uE5uK80b09sTao8tugCxIGb0ExJVl5uTHK59C3rQsUYvVwq/6qdoyrCFjQ/QBpu03Ak6QKBgQDbL5dWGj9aNXSBU65K7OdS4UWWrgveFUBFxLUvc1Ts8wYEMB614VLGHSNgYlGnSe5x71A6bjtXfcxGjb/+u3dUBafxJ65QCwpvRYTS6z/qhy4VSD7CXx/Kb5sNpcfnNW8tX2M7xuBoItiuMgnNCJXB7VrVVM4WkUVfnPS3BdegCwKBgQDOTvd1B/1jm0TqYz1m00Hr+YV/dyecbDv3WQUstR8LOVN+2R9Z9ValPOS8/O+47tGbsMWXNYqTAMhAd/Ub8kveg5ijC9WcYbxbohkni33M8r1aAk/s1QjLTnYfoGPrUBvOivInIcVcEO+7ugxuhByORCBnnOKYtzQTQIE8ZftpNwKBgQCTZoDmlYYvOy2bX1Qh7QlvsjEjMO6oLjBn+u5B99SP+Kr+HAI7HEmXE7dbtSLmVpC1LFQOx1y+7Ml4VRFd1GJeLeOQCLhv+czNobm+QhhctwXlqA0Ul/YAJGfomKlDsqqOn8xTQd5eCbkgBGSU7wYPQXjJaFujz5QQxbPIdXRZmwKBgADKRqJZHHxULOhk5uhM6NS5iOxbDXjI5VXmLmHkc7D8UDiNJlSW3vUVDZ83rMddisn43Fje6J/1gc7VZsfrnqTEhkIhmnjV2v3S2hvPqfSt/VGp7ppumnEE5OjsGVXeYazh1VmXBIV8vx5N8Rw/P0jANAuRi0Cgev+T4KrVjSfzAoGADsK03a+StTBoHRxXEaMV+p1gSOfblEYt2ziezt1oRKcLuYNQ64aP0g0U9cgo0aPD3Q5/e4qSMZUC+fjkdnV6XzU54FLA1gUhogKKCnC66WDYqXfWNuPEBDMDhyC7D/i2aUDRbn1rzdIIfBNsHSpX3WB/DO19giI96+naUaTONGg=
    public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsKPoJoP2eAXiL0qb9RPbS5XrLctQCfN2P8om4in24y1oRjfQQwl/tfkjxQqGKYicuFhRLQBA/poHKpqJaH1JpVhKaTv/BuLy0TqITpCcveJyhIWA/n4SEEtHrDWDzfjkejYZv6yKty0wj+LnGLpKGOZeLEzrNiddHpVWZeOphRufq+LFIOLk7qHuJNyk6om2ixjoW/y0n7Q7rZ2cr5KsLd2Zz9vOvkcbKbYXGIWudJG+M+rLOU1628rrenRUbfYYa0cYzfcDU5HkQZTajOSww8hh4a02ysHPmQZX8bwMz5Sy2EvxxlFUjjWqU3wgrmCBwDV1ZqkywGrpx37Z88DlXQIDAQAB
  redirect-uri: http://127.0.0.1:5500/oauth2.html

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl

logging:
  level:
    com.deepcode.jiaming: debug