server:
  port: 1000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bb_main?serverTimezone=GMT%2B8&userSSL=false&characterEncoding=utf-8
    username: root
    password: mingge123
    driver-class-name: com.mysql.cj.jdbc.Driver
  cache:
    type: redis
    redis:
      cache-null-values: true
  data:
    redis:
      host: localhost
      port: 6379
      password: wzm123

logging:
  level:
    com.winmanboo.bluebook: debug

jiaming:
  mybatis:
    base-package: com.winmanboo.bluebook.main.mapper
