spring:
  datasource:
    url: jdbc:mysql://121.5.183.150:3307/jiaming?serverTimezone=GMT%2B8&userSSL=false&characterEncoding=utf-8
    username: root
    password: jiaming
    driver-class-name: com.mysql.cj.jdbc.Driver
  cache:
    type: redis
    redis:
      cache-null-values: true
  data:
    redis:
      password: jiaming
      host: 121.5.183.150
      port: 6380

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delete
      logic-not-delete-value: 0
      logic-delete-value: 1