spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jiaming?serverTimezone=GMT%2B8&userSSL=false&characterEncoding=utf-8
    username: root
    password: mingge123
    driver-class-name: com.mysql.cj.jdbc.Driver
  cache:
    type: redis
    redis:
      cache-null-values: true
  data:
    redis:
      password: wzm123